<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="lib_luma_denoise_new_a_key"></string>
    <string name="lib_sabre_sharp_2_key">Off (as in library)</string>
    <string name="pref_hot_pixel_key">0</string>
    <string name="lib_pref_g_hue_key_p1_0">0.0</string>
    <string name="pref_double_tap_key">zoom</string>
    <string name="lib_sabre_sharp_tuning_radius_l2_key"></string>
    <string name="pref_qjpg_key">100</string>
    <string name="lib_lighting_key">Off (as in library)</string>
    <string name="lib_sharp_depth_1_key">Off (as in library)</string>
    <string name="lib_custom_patch_count_key_p3_0">10</string>
    <string name="lib_custom_17_key_title"></string>
    <string name="lib_custom_patch_count_key_p3_1">10</string>
    <string name="lib_custom_patch_count_key_p3_2">10</string>
    <string name="lib_max_bracketed_tet_ratio_key"></string>
    <string name="lib_custom_patch_count_key_p3_3">10</string>
    <string name="lib_custom_patch_count_key_p3_4">10</string>
    <string name="lib_pref_satcct_r_key">1.0</string>
    <string name="lib_custom_26_key_title"></string>
    <string name="lib_bracketed_sharpness_threshold_key">Off (as in library)</string>
    <string name="pref_switch_to_previous_mode_command_string">71</string>
    <string name="lib_hot_pixel_suppression_key">Off (as in library)</string>
    <string name="lib_profile_title_key_p6_4">Your profile 6</string>
    <string name="lib_profile_title_key_p6_3">Your profile 6</string>
    <string name="lib_profile_title_key_p6_2">Your profile 6</string>
    <string name="lib_pref_red_coeff_key">1.0</string>
    <string name="lib_luma_dm_sabre_l2_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_radius_l13_key"></string>
    <string name="lib_sabre_sharp_tuning_details_l9_key"></string>
    <string name="pref_frame_count_ns_key">0</string>
    <string name="lib_pref_metering_mode_key">0</string>
    <set name="pref_all_camera_id_list_key">
        <string>0</string>
        <string>1</string>
        <string>2</string>
        <string>3</string>
        <string>4</string>
        <string>5</string>
        <string>6</string>
        <string>7</string>
        <string>8</string>
    </set>
    <string name="pref_manual_focus_far_key">0</string>
    <string name="lib_merge23_luma_dl_sabre_l3a_key">Off (as in library)</string>
    <string name="lib_profile_title_key_p6_1">Your profile 6</string>
    <string name="lib_merge23_luma_dh_sabre_l1b_key">Off (as in library)</string>
    <string name="lib_profile_title_key_p6_0">Your profile 6</string>
    <string name="lib_luma_dl_sabre_l3_key">Off (as in library)</string>
    <string name="lib_sharpen_default_l_2a_key"></string>
    <string name="pref_camera_hdrplus_option_available_key">1</string>
    <string name="lib_pref_blue_coeff_key">1.0</string>
    <string name="pref_slow8x_key">0</string>
    <string name="pref_awb_key">0</string>
    <string name="lib_luma_dh_sabre_l3b_key">Off (as in library)</string>
    <string name="lib_luma_dh_sabre_l5_key">Off (as in library)</string>
    <string name="lib_merge23_luma_dm_sabre_l3a_key">Off (as in library)</string>
    <string name="lib_custom_9_key_value">08EFA752</string>
    <string name="pref_fix_video_brightness_key">1</string>
    <string name="lib_custom_13_key_value">05F02D1E</string>
    <string name="pref_r_hue_key">0</string>
    <string name="lib_pref_b_hue_key">0</string>
    <boolean name="finish_long_shot_capture" value="true" />
    <string name="lib_sabre_contrast_key">Off (as in library)</string>
    <string name="lib_merge23_luma_dl_sabre_l2b_key">Off (as in library)</string>
    <string name="lib_gpu_shadows_key">0</string>
    <string name="lib_gpu_vignette_end_key">0</string>
    <string name="lib_sabre_sharp_tuning_radius_l1_key"></string>
    <string name="lib_zoom_ratio_key">2.0</string>
    <string name="pref_camera_hdr_plus_back_flashmode_thermally_disabled_key">0</string>
    <string name="lib_sharp_gain_macro_key"></string>
    <string name="info_board_key">kalama</string>
    <string name="lib_luma_denoise_new_b_key"></string>
    <int name="tooltip_impression_trigger_count_for_long_exposure_smarts_chip" value="2" />
    <string name="pref_raw_key">0</string>
    <string name="lib_custom_22_key_title"></string>
    <string name="lib_custom_patch_count_key_p5_0">10</string>
    <string name="lib_sharp_depth_2_key">Off (as in library)</string>
    <string name="lib_custom_patch_count_key_p5_1">10</string>
    <string name="lib_custom_patch_count_key_p5_2">10</string>
    <string name="lib_custom_patch_count_key_p5_3">10</string>
    <string name="lib_custom_patch_count_key_p5_4">10</string>
    <string name="pref_awb_bg_coeff_key">1.0</string>
    <string name="pref_chameleon_control_key">0</string>
    <string name="lib_custom_29_key_value">01F02D1E</string>
    <string name="lib_sabre_sharp_tuning_radius_l12_key"></string>
    <string name="lib_sabre_sharp_3_key">Off (as in library)</string>
    <string name="lib_gamma_custom_key"></string>
    <string name="lib_pref_satcct_c_key">1.0</string>
    <string name="lib_profile_title_key_p4_4">Your profile 4</string>
    <string name="pref_c2a_key">3</string>
    <string name="lib_with_lowest_score_key">Off (as in library)</string>
    <string name="lib_luma_dl_sabre_l2_key">Off (as in library)</string>
    <string name="lib_luma_dh_sabre_l4a_key">Off (as in library)</string>
    <string name="pref_fix_spatial_gain_map_key">0</string>
    <string name="lib_custom_patch_count_key">35</string>
    <string name="pref_manual_opmode_slowmo_key">0</string>
    <string name="lib_pref_cct_wb_intensity_key">1.0</string>
    <string name="lib_sharp_gain_micro_key"></string>
    <string name="lib_profile_title_key_p4_3">Your profile 4</string>
    <string name="lib_profile_title_key_p4_2">Your profile 4</string>
    <string name="lib_profile_title_key_p4_1">Your profile 4</string>
    <string name="lib_profile_title_key_p4_0">Your profile 4</string>
    <string name="lib_custom_13_key_title"></string>
    <string name="pref_camera_raw_output_option_available_key">1</string>
    <string name="lib_smoothing_new_key">Off (as in library)</string>
    <string name="lib_luma_dh_sabre_l3a_key">Off (as in library)</string>
    <string name="lib_sharp_big_key">Off (as in library)</string>
    <string name="lib_merge23_luma_dl_sabre_l3b_key">Off (as in library)</string>
    <string name="lib_p5_nm_gain_multiplier_key"></string>
    <string name="lib_gpu_wb_tint_key">0</string>
    <string name="lib_luma_dl_sabre_l4b_key">Off (as in library)</string>
    <string name="pref_lens_title_key"></string>
    <string name="pref_vid_prefix_key">AGC_VID_</string>
    <string name="lib_sharpness_b_key"></string>
    <string name="lib_dehazed_regulator_2_key">Off (as in library)</string>
    <string name="lib_merge23_luma_dl_sabre_l2a_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_details_l10_key"></string>
    <string name="lib_merge23_luma_dm_sabre_l3b_key">Off (as in library)</string>
    <string name="lib_polysharp_radius_med_key"></string>
    <string name="pref_frame_count_zsl_key">0</string>
    <string name="lib_pref_gamma_custom_key_p1_0">0.00,0.00,0.25,0.25,0.50,0.50,0.75,0.75,1.00,1.00</string>
    <string name="lib_custom_17_key_value">F628BC3F</string>
    <string name="co_b_key">1.9878738E-12</string>
    <string name="lib_pref_gamma_custom_key_p1_2">0.00,0.00,0.25,0.25,0.50,0.50,0.75,0.75,1.00,1.00</string>
    <string name="pref_audio_zoom_key">0</string>
    <string name="lib_pref_gamma_custom_key_p1_3">0.00,0.00,0.25,0.25,0.50,0.50,0.75,0.75,1.00,1.00</string>
    <string name="lib_pref_gamma_custom_key_p1_4">0.00,0.00,0.25,0.25,0.50,0.50,0.75,0.75,1.00,1.00</string>
    <string name="lib_noise_reduction_adjust_key"></string>
    <string name="pref_zoom_in_command_string">19</string>
    <string name="lib_enable_color_key_p2_2">1</string>
    <string name="lib_sabre_sharp_tuning_details_l7_key"></string>
    <string name="lib_enable_color_key_p2_1">1</string>
    <string name="pref_ois_key">1</string>
    <string name="lib_enable_color_key_p2_0">1</string>
    <string name="pref_camera_dynamic_depth_enabled_key">0</string>
    <string name="lib_hdr_sabre_calc_val_1_key">Off (as in library)</string>
    <string name="pref_manual_opmode_photo_key">0</string>
    <string name="pref_has_shown_longp_education">1</string>
    <string name="lib_enable_color_key_p2_4">1</string>
    <string name="lib_enable_color_key_p2_3">1</string>
    <string name="lib_custom_25_key_value">08EFA752</string>
    <string name="pref_camera_grid_lines_mode">3</string>
    <string name="lib_custom_patch_count_key_p7_0">10</string>
    <string name="lib_custom_patch_count_key_p7_1">10</string>
    <string name="lib_luma_dl_sabre_l1_key">Off (as in library)</string>
    <string name="lib_custom_patch_count_key_p7_2">10</string>
    <string name="lib_custom_patch_count_key_p7_3">10</string>
    <string name="patch_profile_key_0">0</string>
    <string name="lib_custom_patch_count_key_p7_4">10</string>
    <string name="lib_setuxmode_key">Off (as in library)</string>
    <string name="lib_lut_id_key_p1_4">-1</string>
    <string name="lib_lut_id_key_p1_3">-1</string>
    <string name="lib_lut_id_key_p1_2">-1</string>
    <string name="lib_hdr_effect_intensity_key">Off (as in library)</string>
    <string name="lib_lut_id_key_p1_0">-1</string>
    <string name="lib_merge23_luma_dm_sabre_l4a_key">Off (as in library)</string>
    <string name="lib_luma_b_key"></string>
    <string name="lib_luma_smoothing_key">Off (as in library)</string>
    <string name="pref_shasta_key">0</string>
    <string name="lib_luma_dm_sabre_l4b_key">Off (as in library)</string>
    <string name="lib_luma_dh_sabre_l3_key">Off (as in library)</string>
    <string name="lib_pref_satcct_b_key">1.0</string>
    <string name="lib_profile_action_key">android.media.action.STILL_IMAGE_CAMERA</string>
    <string name="rg_key">-0.937</string>
    <string name="pref_camera_enable_iris">0</string>
    <string name="lib_gpu_wb_temperature_key">5000.0</string>
    <string name="lib_profile_title_key_p2_4">Your profile 2</string>
    <string name="lib_profile_title_key_p2_3">Your profile 2</string>
    <string name="lib_profile_title_key_p2_2">Your profile 2</string>
    <string name="pref_satcct_key">1.0</string>
    <string name="lib_profile_title_key_p2_1">Your profile 2</string>
    <string name="lib_profile_title_key_p2_0">Your profile 2</string>
    <string name="lib_pref_red_coeff_key_p0_0">1.0</string>
    <string name="lib_brightness_intensity_key">Off (as in library)</string>
    <string name="lib_luma_dl_sabre_l4a_key">Off (as in library)</string>
    <string name="pref_frame_count_ns_key_2">27</string>
    <string name="pref_frame_count_ns_key_3">27</string>
    <string name="lib_custom_31_key_value">0310241E</string>
    <string name="pref_frame_count_ns_key_0">27</string>
    <string name="pref_frame_count_ns_key_1">27</string>
    <string name="pref_frame_count_ns_key_4">27</string>
    <string name="lib_pref_red_coeff_key_p0_4">1.0</string>
    <string name="lib_pref_red_coeff_key_p0_3">1.0</string>
    <string name="lib_pref_red_coeff_key_p0_2">1.0</string>
    <string name="pref_config_nickname_key">@antykat</string>
    <string name="lib_sharpness_a_key"></string>
    <string name="lib_gpu_rgb_blue_key">0</string>
    <string name="pref_frame_count_key">0</string>
    <string name="lib_shastaforce_key">Off (as in library)</string>
    <string name="lib_pref_frame_count_ns_key">0</string>
    <string name="lib_with_tet_mismatch_key">Off (as in library)</string>
    <string name="pref_opmode_amber_key">0</string>
    <string name="lib_custom_16_key_value">1F857F41</string>
    <string name="lib_rg_key">-0.937</string>
    <string name="lib_merge23_luma_dl_sabre_l4a_key">Off (as in library)</string>
    <string name="lib_chroma_smoothing_key">Off (as in library)</string>
    <string name="lib_custom_26_key_value">01F02D1E</string>
    <string name="lib_pref_tone_custom_key_p1_4">0.00,0.00,0.25,0.25,0.50,0.50,0.75,0.75,1.00,1.00</string>
    <string name="pref_switch_long_action_key">lib_group_default_key</string>
    <string name="lib_pref_tone_custom_key_p1_3">0.00,0.00,0.25,0.25,0.50,0.50,0.75,0.75,1.00,1.00</string>
    <string name="lib_custom_1_key_value">E0F5034F</string>
    <string name="lib_custom_28_key_address">0332B534</string>
    <string name="lib_max_exp_ms_key">0.0</string>
    <string name="lib_custom_27_key_address">0332B530</string>
    <string name="pref_merge_key">0</string>
    <string name="lib_pref_tone_custom_key_p1_2">0.00,0.00,0.25,0.25,0.50,0.50,0.75,0.75,1.00,1.00</string>
    <string name="lib_smoothing_spatial_key">Off (as in library)</string>
    <string name="lib_pref_tone_custom_key_p1_0">0.00,0.00,0.25,0.25,0.50,0.50,0.75,0.75,1.00,1.00</string>
    <string name="info_fingerprint_key">Xiaomi/fuxi_eea/fuxi:14/UKQ1.230804.001/V816.0.8.0.UMCEUXM:user/release-keys</string>
    <string name="lib_sharpen_default_h_3_key"></string>
    <string name="lib_hdr_range_minus_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_details_l11_key"></string>
    <string name="lib_enable_color_key_p0_4">0</string>
    <string name="lib_enable_color_key_p0_3">0</string>
    <string name="pref_frame_count_astro_key">0</string>
    <string name="lib_enable_color_key_p0_2">0</string>
    <string name="lib_custom_29_key_title"></string>
    <string name="pref_check_hal_update_after_gca_version">66959874</string>
    <string name="lib_hdr_sabre_calc_val_2_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_details_l12_key"></string>
    <string name="lib_sabre_brigthtness_key">Off (as in library)</string>
    <string name="lib_dissimilar_psl_frames_for_nightsight_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_details_l8_key"></string>
    <string name="lib_custom_20_key_address">01E147C8</string>
    <string name="lib_custom_24_key_address">025D2018</string>
    <string name="panorama_upgrade_version">1</string>
    <string name="lib_enable_color_key_p0_0">0</string>
    <string name="lib_custom_30_key_value">01F06F1E</string>
    <string name="lib_sharpen_default_vh_2a_key"></string>
    <string name="pref_antibanding_key">3</string>
    <string name="black_level_3_key">64.0</string>
    <string name="lib_pref_awb_key">0</string>
    <string name="lib_brightness_key"></string>
    <string name="lib_pref_awb_bg_coeff_key">1.0</string>
    <string name="pref_iso_noise_coeff_key">0.5</string>
    <string name="pref_switch_camera_command_string">47</string>
    <string name="pref_switch_to_next_mode_command_string">72</string>
    <string name="lib_merge23_luma_dh_sabre_l1a_key">Off (as in library)</string>
    <string name="gb_key">0.085</string>
    <string name="lib_merge23_luma_dl_sabre_l1b_key">Off (as in library)</string>
    <string name="lib_pref_color_transform_key_p0_0">0</string>
    <string name="lib_luma_a_key"></string>
    <string name="lib_pref_color_transform_key_p0_3">0</string>
    <string name="lib_pref_color_transform_key_p0_2">0</string>
    <string name="lib_pref_color_transform_key_p0_4">0</string>
    <string name="lib_sabre_sharp_tuning_radius_l14_key"></string>
    <string name="lib_iso_key"></string>
    <string name="pref_device_key_0">4</string>
    <string name="lib_profile_title_key_p0_4">Standard</string>
    <string name="pref_device_key_2">4</string>
    <string name="lib_profile_title_key_p0_3">Standard</string>
    <string name="pref_device_key_1">4</string>
    <string name="lib_profile_title_key_p0_2">Standard</string>
    <string name="lib_sabre_denoise_control_key">Off (as in library)</string>
    <string name="pref_device_key_4">4</string>
    <string name="lib_profile_title_key_p0_1">Standard</string>
    <string name="pref_device_key_3">4</string>
    <string name="lib_profile_title_key_p0_0">Natural</string>
    <string name="lib_luma_dm_sabre_l4a_key">Off (as in library)</string>
    <string name="lib_denoise_key"></string>
    <string name="lib_custom_31_key_title"></string>
    <string name="lib_shadows_key">Off (as in library)</string>
    <string name="lib_custom_2_key_title"></string>
    <string name="pref_update_available_chip_dismissal_times">0</string>
    <string name="lib_custom_30_key_address">038F105C</string>
    <string name="lib_sabre_sharp_tuning_radius_l15_key"></string>
    <string name="pref_manual_opmode_video_key">0</string>
    <string name="pref_focus_lock_time_key">0</string>
    <string name="pref_opmode_ns_key">0</string>
    <string name="pref_social_app_com_google_android_youtube">0</string>
    <string name="pref_frame_count_zsl_key_4">15</string>
    <string name="pref_frame_count_zsl_key_3">15</string>
    <string name="lib_custom_13_key_address">0371399C</string>
    <string name="pref_frame_count_zsl_key_2">15</string>
    <string name="pref_black_level_dynamic_key">0</string>
    <string name="pref_frame_count_zsl_key_1">15</string>
    <string name="lib_luma_dh_sabre_l4_key">Off (as in library)</string>
    <string name="as_b_key">4.9889366E-7</string>
    <string name="pref_frame_count_zsl_key_0">15</string>
    <string name="pref_model_key_0">0</string>
    <string name="pref_model_key_4">0</string>
    <string name="lib_pref_upscale_key">0</string>
    <string name="lib_custom_17_key_address">004664F4</string>
    <string name="lib_custom_2_key_enabled">1</string>
    <string name="pref_sensor_color_filter_key">0</string>
    <string name="pref_shutter_command_string">66</string>
    <string name="pref_has_checked_gouda_mode">1</string>
    <string name="lib_custom_6_key_enabled">1</string>
    <string name="lib_rb_key">0.257</string>
    <string name="lib_fine_spatial_min_1_key">Off (as in library)</string>
    <string name="lib_exposition_key"></string>
    <string name="lib_custom_8_key_enabled">1</string>
    <string name="lib_sabre_detail_key">Off (as in library)</string>
    <string name="lib_pref_satcct_r_key_p0_0">1.0</string>
    <string name="pref_opmode_video_key_4">32828</string>
    <string name="lib_merge23_luma_dm_sabre_l5a_key">Off (as in library)</string>
    <string name="lib_pref_satcct_r_key_p0_2">1.0</string>
    <string name="lib_pref_satcct_r_key_p0_3">1.0</string>
    <string name="lib_pref_satcct_r_key_p0_4">1.0</string>
    <string name="pref_opmode_video_key_0">32828</string>
    <string name="lib_spatial_gain_map_1_key">Off (as in library)</string>
    <string name="lib_custom_25_key_title"></string>
    <string name="lib_hdr_range_plus_key">Off (as in library)</string>
    <string name="lib_gpu_unsharp_intensity_key">0</string>
    <string name="lib_sharpen_default_m_1a_key"></string>
    <string name="lib_pref_iso_noise_key">0</string>
    <string name="lib_custom_1_key_title"></string>
    <string name="pref_model_key">0</string>
    <string name="info_version_key">AGC9.1 V15.0 (be0c2fd5) 2024-04-24 07:44</string>
    <string name="lib_merge23_luma_dm_sabre_l1b_key">Off (as in library)</string>
    <string name="lib_merge23_luma_dl_sabre_l4b_key">Off (as in library)</string>
    <string name="pref_camera_back_flashmode_key">off</string>
    <string name="pref_lens_title_short_key"></string>
    <string name="pref_social_app_org_telegram_messenger">0</string>
    <string name="lib_fix_sabre_noise_key">Off (as in library)</string>
    <string name="lib_luma_noise_key"></string>
    <string name="pref_aux_key">0</string>
    <string name="lib_sabre_sharp_tuning_radius_l6_key"></string>
    <string name="lib_hdr_ratio_3_key">Off (as in library)</string>
    <string name="lib_enable_color_key_p5_3">1</string>
    <string name="lib_enable_color_key_p5_2">1</string>
    <string name="lib_enable_color_key_p5_1">1</string>
    <string name="lib_bayer_noise_model_halide_1_key">Off (as in library)</string>
    <string name="lib_shasta_max_exp_ms_key">0.0</string>
    <string name="lib_enable_color_key_p5_0">1</string>
    <string name="lib_sabre_sharp_tuning_l18_key"></string>
    <string name="pref_camera_video_back_flashmode_thermally_disabled_key">0</string>
    <string name="lib_lut_key_p1_4">null</string>
    <string name="lib_enable_color_key_p5_4">1</string>
    <string name="lib_lut_key_p1_2">null</string>
    <string name="lib_lut_key_p1_3">null</string>
    <string name="lib_lut_key_p1_0">null</string>
    <string name="lib_custom_23_key_title"></string>
    <string name="lib_dehazed_expo_key">Off (as in library)</string>
    <string name="lib_temporal_radius_2_key">Off (as in library)</string>
    <string name="pref_watermark_type_key">0</string>
    <string name="lib_merge23_luma_dh_sabre_l3b_key">Off (as in library)</string>
    <string name="lib_pref_model_key">0</string>
    <string name="lib_merge23_luma_dl_sabre_l4_key">Off (as in library)</string>
    <string name="pref_double_tap_launch_edu_count">2</string>
    <string name="pref_camera_resolution">full</string>
    <string name="lib_volume_processing_key">Off (as in library)</string>
    <string name="lib_custom_30_key_title"></string>
    <string name="lib_custom_18_key_title"></string>
    <string name="bg_key">-0.914</string>
    <string name="pref_upscale_key">0</string>
    <string name="lib_sabre_sharp_tuning_l1_key"></string>
    <string name="lib_gpu_rgb_green_key">0</string>
    <string name="pref_g_hue_key">0</string>
    <string name="lib_pref_r_hue_key_p0_0">0.0</string>
    <string name="lib_pref_r_hue_key_p0_3">0.0</string>
    <string name="lib_pref_r_hue_key_p0_4">0.0</string>
    <string name="lib_hdr_range_limit_2_key">Off (as in library)</string>
    <string name="lib_pref_r_hue_key_p0_2">0.0</string>
    <string name="pref_opmode_video_key">0</string>
    <string name="pref_has_set_social_share_apps">1</string>
    <boolean name="pref_awb_switch_key" value="false" />
    <string name="pref_upgrade_version">27</string>
    <string name="lib_pref_awb_rg_coeff_key">1.0</string>
    <string name="lib_sharpen_default_vl_2a_key"></string>
    <string name="lib_downsample_factor_key">Off (as in library)</string>
    <string name="pref_max_zoom_key">0</string>
    <string name="lib_sharpen_default_vl_1a_key"></string>
    <string name="pref_video_fps_4k_key">FPS_60</string>
    <string name="lib_spatial_gain_map_2_key">Off (as in library)</string>
    <string name="lib_luma_dl_sabre_l3a_key">Off (as in library)</string>
    <string name="lib_pref_frame_count_key">0</string>
    <string name="pref_lens_title_short_key_3"></string>
    <string name="pref_camera_recordlocation_key">0</string>
    <string name="pref_lens_title_short_key_4">VID</string>
    <boolean name="finish_video_capture" value="true" />
    <string name="lib_gpu_contrast_key">1.0</string>
    <string name="pref_lens_title_short_key_0">M</string>
    <string name="pref_lens_title_short_key_1">UW</string>
    <string name="lib_merge23_luma_dm_sabre_l1a_key">Off (as in library)</string>
    <string name="pref_lens_title_short_key_2">TEL</string>
    <string name="lib_enable_color_key_p3_1">1</string>
    <string name="lib_enable_color_key_p3_0">1</string>
    <string name="lib_merge23_luma_dl_sabre_l5_key">Off (as in library)</string>
    <string name="pref_opmode_time_lapse_key">0</string>
    <string name="lib_sabre_sharp_tuning_l17_key"></string>
    <string name="lib_enable_color_key_p3_4">1</string>
    <string name="lib_custom_27_key_title"></string>
    <string name="lib_enable_color_key_p3_3">1</string>
    <string name="lib_merge23_luma_dh_sabre_l3a_key">Off (as in library)</string>
    <string name="lib_enable_color_key_p3_2">1</string>
    <string name="pref_camera_single_shot_sound_key">0</string>
    <string name="lib_bayer_noise_model_halide_2_key">Off (as in library)</string>
    <string name="lib_merge23_luma_dm_sabre_l2a_key">Off (as in library)</string>
    <string name="lib_suppress_hot_pixels_key">Off (as in library)</string>
    <string name="lib_max_bracketing_frames_key"></string>
    <string name="lib_custom_14_key_address">00A0C3BC</string>
    <string name="lib_sabre_sharp_tuning_radius_l5_key"></string>
    <string name="lib_custom_31_key_address">03693278</string>
    <string name="pref_hdr_tooltip_countdown">0</string>
    <string name="lib_luma_dl_sabre_l3b_key">Off (as in library)</string>
    <string name="pref_expcomp_portrait_key">0</string>
    <string name="lib_gr_key">-0.148</string>
    <string name="pref_fix_resolution_key">0</string>
    <string name="lib_sharpen_default_h_1a_key"></string>
    <string name="lib_custom_16_key_address">004664F0</string>
    <string name="lib_custom_3_key_enabled">1</string>
    <string name="lib_custom_21_key_title"></string>
    <string name="lib_exposure_darker_key"></string>
    <string name="lib_hdr_range_limit_1_key">Off (as in library)</string>
    <string name="lib_custom_5_key_enabled">1</string>
    <string name="pref_af_mode_back">0</string>
    <string name="pref_camera_catcher_key">0</string>
    <string name="lib_fix_shasta_merge_key">Off (as in library)</string>
    <string name="lib_exposure_darker_2_key"></string>
    <string name="lib_sabre_sharp_tuning_radius_l11_key"></string>
    <string name="lib_sharpen_default_l_3a_key"></string>
    <string name="rr_key">1.679</string>
    <string name="lib_raisr_small_key">Off (as in library)</string>
    <string name="pref_watermark_time_format_key"></string>
    <string name="custom_lib_open_key">gcastartup</string>
    <string name="lib_sabre_sharp_tuning_radius_l4_key"></string>
    <string name="lib_custom_18_key_value">E17A0440</string>
    <string name="lib_portrait_relighting_option_key">Off (as in library)</string>
    <string name="lib_shot_noise_factor_key">Off (as in library)</string>
    <string name="do_b_key">-8.484603E-8</string>
    <string name="gr_key">-0.148</string>
    <string name="lib_spatial_gain_map_3_key">Off (as in library)</string>
    <string name="lib_custom_7_key_address">038F5758</string>
    <string name="lib_luma_dh_sabre_l4b_key">Off (as in library)</string>
    <string name="lib_luma_dl_sabre_l5_key">Off (as in library)</string>
    <string name="lib_merge23_luma_dm_sabre_l2b_key">Off (as in library)</string>
    <string name="pref_minimum_focus_distance_key">0</string>
    <string name="pref_satcct_y_key">1.0</string>
    <string name="lib_enable_cct_key_p0_0">0</string>
    <string name="pref_dotfix_key">0</string>
    <string name="lib_luma_dm_sabre_l2b_key">Off (as in library)</string>
    <string name="pref_volume_key_action">shutter</string>
    <string name="lib_custom_19_key_value">00F02D1E</string>
    <string name="lib_pref_iso_noise_coeff_key">0.5</string>
    <string name="lib_zipper_2_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_l3_key"></string>
    <string name="pref_color_transform_key">0</string>
    <string name="lib_pref_noise_model_key">0</string>
    <string name="lib_pref_global_hue_key">0</string>
    <string name="lib_custom_25_key_address">025D201C</string>
    <string name="pref_vffps_high_key">30</string>
    <string name="pref_satcct_g_key">1.0</string>
    <string name="lib_pref_green_coeff_key_p0_2">1.0</string>
    <string name="lib_pref_green_coeff_key_p0_0">1.0</string>
    <string name="pref_camera_switch_position_key">right</string>
    <string name="pref_upscaling_key">0</string>
    <string name="pref_camera_hdr_plus_key">on</string>
    <string name="lib_rr_key">1.679</string>
    <string name="pref_bitrate_key">0</string>
    <string name="lib_enable_cct_key_p0_4">0</string>
    <string name="pref_xml_path_key">/Download/AGC.9.1/configs/</string>
    <string name="lib_enable_cct_key_p0_3">0</string>
    <string name="lib_enable_cct_key_p0_2">0</string>
    <string name="lib_custom_23_key_value">01103E1E</string>
    <string name="lib_pref_green_coeff_key_p0_3">1.0</string>
    <string name="lib_pref_green_coeff_key_p0_4">1.0</string>
    <string name="pref_opmode_portrait_key">0</string>
    <string name="lib_custom_15_key_enabled">1</string>
    <string name="lib_sabre_sharp_tuning_radius_l10_key"></string>
    <string name="info_hardware_key">qcom</string>
    <string name="info_sdk_key">34</string>
    <string name="lib_sharpen_default_vh_3a_key"></string>
    <string name="bs_r_key">1.0785347E-5</string>
    <string name="lib_custom_patch_count_key_p1_0">10</string>
    <string name="pref_camera_raw_output_notice_shown_key">1</string>
    <string name="lib_custom_patch_count_key_p1_1">10</string>
    <string name="lib_custom_patch_count_key_p1_2">10</string>
    <string name="lib_custom_patch_count_key_p1_3">10</string>
    <string name="lib_custom_patch_count_key_p1_4">10</string>
    <string name="lib_custom_22_key_value">03F03D1E</string>
    <string name="lib_hdr_effect_key">Off (as in library)</string>
    <string name="lib_luma_dm_sabre_l5a_key">Off (as in library)</string>
    <string name="lib_bg_key">-0.914</string>
    <string name="pref_gcam_version_key">9.1</string>
    <string name="lib_custom_22_key_address">03693234</string>
    <string name="lib_pref_satcct_g_key_p1_0">1.0</string>
    <string name="pref_blue_coeff_key">1.0</string>
    <string name="pref_camera_sounds_key">0</string>
    <string name="lib_custom_21_key_value">00F02F1E</string>
    <string name="lib_fine_spatial_min_2_key">Off (as in library)</string>
    <string name="lib_average_ldr_tet_key"></string>
    <string name="bs_gb_key">1.0785347E-5</string>
    <string name="lib_sabre_sharp_tuning_radius_l3_key"></string>
    <string name="lib_custom_26_key_enabled">1</string>
    <string name="lib_enable_color_key_p7_1">1</string>
    <string name="nr_isostep_key">6400</string>
    <string name="lib_enable_color_key_p7_0">1</string>
    <string name="pref_switch_front_restart_key">1</string>
    <string name="lib_hardmerge_key">1</string>
    <string name="lib_custom_4_key_address">025D26B8</string>
    <string name="lib_enable_color_key_p7_4">1</string>
    <string name="rb_key">0.257</string>
    <string name="lib_enable_color_key_p7_3">1</string>
    <string name="lib_pref_g_hue_key">0</string>
    <string name="lib_sabre_sharp_tuning_l2_key"></string>
    <string name="lib_enable_color_key_p7_2">1</string>
    <string name="lib_highlight_fix_key">1</string>
    <string name="lib_luma_dl_sabre_l4_key">Off (as in library)</string>
    <string name="lib_gpu_hue_key">90</string>
    <string name="pref_expcomp_key">0</string>
    <string name="perf_has_run_second_education">1</string>
    <string name="lib_ns_sharp_delta_factor_key">Off (as in library)</string>
    <string name="lib_high_lighting_key">Off (as in library)</string>
    <string name="info_brand_key">Xiaomi</string>
    <string name="pref_micro_video_key">0</string>
    <string name="lib_noisemodelunblock_key">1</string>
    <string name="lib_custom_11_key_address">025D27F0</string>
    <string name="lib_profile_title_key_p7_4">Your profile 7</string>
    <string name="lib_profile_title_key_p7_3">Your profile 7</string>
    <string name="lib_profile_title_key_p7_2">Your profile 7</string>
    <string name="lib_profile_title_key_p7_1">Your profile 7</string>
    <string name="pref_has_checked_lens_mode">0</string>
    <string name="lib_custom_24_key_title"></string>
    <string name="co_gb_key">1.9878738E-12</string>
    <string name="pref_noise_model_key">0</string>
    <string name="lib_profile_title_key_p7_0">Your profile 7</string>
    <string name="lib_preserve_highlights_key">Off (as in library)</string>
    <string name="lib_custom_19_key_address">024ED8AC</string>
    <string name="do_r_key">-8.484603E-8</string>
    <string name="key_promote_launch_wear">0</string>
    <string name="pref_last_installed_version_code">66959874</string>
    <string name="lib_sharp_gain_key"></string>
    <string name="lib_custom_7_key_value">E1F5034F</string>
    <string name="lib_custom_30_key_enabled">0</string>
    <string name="lib_sharpen_default_m_3a_key"></string>
    <string name="lib_sabre_sharp_tuning_radius_l9_key"></string>
    <string name="lib_custom_32_key_enabled">0</string>
    <string name="lib_custom_11_key_value">08EFA752</string>
    <string name="lib_pref_green_coeff_key">1.0</string>
    <string name="pref_b_hue_key">0</string>
    <string name="lib_custom_31_key_enabled">0</string>
    <string name="lib_sabre_burst_merge_1_key">Off (as in library)</string>
    <string name="lib_zipper_3_key">Off (as in library)</string>
    <string name="lib_merge23_luma_dh_sabre_l2_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_l15_key"></string>
    <string name="lib_gpu_exposure_key">0</string>
    <string name="lib_gpu_saturation_key">1.0</string>
    <string name="pref_has_checked_cheetah_mode">1</string>
    <string name="pref_mode_vesper_level">0</string>
    <string name="lib_luma_dl_sabre_l1b_key">Off (as in library)</string>
    <string name="lib_custom_29_key_enabled">0</string>
    <string name="lib_sharpen_default_h_2a_key"></string>
    <string name="lib_custom_28_key_enabled">1</string>
    <string name="pref_manual_opmode_portrait_key">0</string>
    <string name="lib_profile_title_key"></string>
    <string name="lib_custom_20_key_value">00D02D1E</string>
    <string name="lib_pref_g_hue_key_p0_0">0.0</string>
    <string name="lib_pref_satcct_y_key">1.0</string>
    <string name="lib_pref_g_hue_key_p0_4">0.0</string>
    <string name="lib_pref_g_hue_key_p0_2">0.0</string>
    <string name="lib_pref_g_hue_key_p0_3">0.0</string>
    <string name="lib_custom_patch_count_key_p4_0">10</string>
    <string name="lib_custom_patch_count_key_p4_1">10</string>
    <string name="lib_custom_patch_count_key_p4_2">10</string>
    <string name="lib_custom_patch_count_key_p4_3">10</string>
    <string name="lib_custom_patch_count_key_p4_4">10</string>
    <string name="pref_manual_focus_near_key">0</string>
    <string name="lib_sharpen_default_vh_2_key"></string>
    <string name="dev_setting_filter_key">zoom</string>
    <string name="br_key">0.093</string>
    <string name="lib_sect_key">Off (as in library)</string>
    <string name="lib_temporal_radius_key">Off (as in library)</string>
    <string name="pref_slow4x_key">0</string>
    <string name="lib_sabre_2_key">Off (as in library)</string>
    <string name="lib_profile_title_key_p5_4">Your profile 5</string>
    <string name="lib_profile_title_key_p5_3">Your profile 5</string>
    <string name="lib_custom_15_key_title"></string>
    <string name="lib_custom_28_key_title"></string>
    <string name="pref_camera_selfie_mirror_key">1</string>
    <string name="lib_sharpen_default_vl_3a_key"></string>
    <string name="pref_c2a_key_0">0</string>
    <string name="lib_resamplmethod_key">Off (as in library)</string>
    <string name="lib_gpu_sharpness_key">0</string>
    <string name="lib_profile_title_key_p5_2">Your profile 5</string>
    <string name="lib_profile_title_key_p5_1">Your profile 5</string>
    <string name="lib_profile_title_key_p5_0">Your profile 5</string>
    <string name="pref_c2a_key_2">0</string>
    <string name="pref_c2a_key_1">0</string>
    <string name="pref_c2a_key_4">0</string>
    <string name="lib_merge23_luma_dh_sabre_l5a_key">Off (as in library)</string>
    <string name="pref_awbratio_key">0</string>
    <string name="pref_c2a_key_3">0</string>
    <string name="co_gr_key">1.9878738E-12</string>
    <string name="pref_patch_profile_count_key">9</string>
    <string name="lib_custom_12_key_enabled">1</string>
    <string name="lib_custom_16_key_enabled">0</string>
    <string name="lib_custom_4_key_title"></string>
    <string name="lib_luma_dl_sabre_l1a_key">Off (as in library)</string>
    <string name="lib_max_short_frames_key"></string>
    <string name="lib_merge23_luma_dl_sabre_l1_key">Off (as in library)</string>
    <string name="lib_custom_14_key_enabled">1</string>
    <string name="perf_has_shown_options_bar">1</string>
    <string name="lib_custom_10_key_enabled">1</string>
    <string name="lib_sabre_sharp_tuning_l5_key"></string>
    <string name="lib_lutnoisefix_key"></string>
    <string name="lib_custom_3_key_value">E0F5034F</string>
    <string name="pref_mode_vesperad_option">0</string>
    <string name="pref_manual_iso_noise_key">6400</string>
    <string name="lib_contrast_black_2_key">Off (as in library)</string>
    <boolean name="hdrnet_enabled" value="false" />
    <string name="lib_sabre_sharp_tuning_details_l1_key"></string>
    <string name="lib_merge23_luma_dh_sabre_l1_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_l16_key"></string>
    <string name="lib_hdr_ratio_limit_override_key">Off (as in library)</string>
    <string name="bs_gr_key">1.0785347E-5</string>
    <string name="lib_raisr_med_key">Off (as in library)</string>
    <string name="lib_color_processing_key">Off (as in library)</string>
    <string name="lib_merge23_luma_dh_sabre_l4b_key">Off (as in library)</string>
    <string name="lib_custom_18_key_enabled">1</string>
    <string name="lib_darken_light_key"></string>
    <string name="lib_custom_25_key_enabled">1</string>
    <string name="lib_sabre_sharp_tuning_details_l2_key"></string>
    <string name="lib_custom_23_key_enabled">0</string>
    <string name="lib_custom_27_key_enabled">1</string>
    <string name="pref_camera_front_flashmode_key">off</string>
    <string name="lib_custom_1_key_address">025D2888</string>
    <string name="pref_video_fps_vb_key">FPS_30</string>
    <string name="lib_max_frame_count_key"></string>
    <string name="pref_camera_hdr_plus_override_key"></string>
    <string name="perf_has_run_first_education">1</string>
    <string name="lib_sharpen_default_vh_1_key"></string>
    <string name="lib_custom_3_key_address">025D26B4</string>
    <string name="pref_black_level_key">0</string>
    <string name="lib_custom_patch_count_key_p6_0">10</string>
    <string name="lib_custom_patch_count_key_p6_1">10</string>
    <string name="lib_sabre_sharp_tuning_l4_key"></string>
    <string name="lib_custom_patch_count_key_p6_2">10</string>
    <string name="pref_motion_key">1</string>
    <string name="lib_custom_patch_count_key_p6_3">10</string>
    <string name="lib_custom_patch_count_key_p6_4">10</string>
    <string name="lib_custom_24_key_value">E0F5030F</string>
    <string name="lib_luma_dm_sabre_l2a_key">Off (as in library)</string>
    <string name="pref_aux_front_key">0</string>
    <string name="bs_b_key">1.0785347E-5</string>
    <string name="lib_custom_19_key_title"></string>
    <string name="lib_custom_21_key_enabled">1</string>
    <string name="lib_gpu_gamma_key">1.0</string>
    <string name="info_device_key">fuxi</string>
    <string name="pref_cct_wb_offset_key">1.0</string>
    <string name="pref_manual_upscale_key">20</string>
    <string name="pref_noise_model_key_4">63</string>
    <string name="pref_noise_model_key_0">63</string>
    <string name="pref_noise_model_key_1">53</string>
    <string name="pref_noise_model_key_2">52</string>
    <string name="pref_camera_kepler_enabled_key">1</string>
    <string name="lib_sabre_3_key">Off (as in library)</string>
    <string name="lib_luma_dl_sabre_l2a_key">Off (as in library)</string>
    <string name="lib_profile_title_key_p3_4">Your profile 3</string>
    <string name="lib_profile_title_key_p3_3">Your profile 3</string>
    <string name="lib_profile_title_key_p3_2">Your profile 3</string>
    <string name="lib_profile_title_key_p3_1">Your profile 3</string>
    <string name="lib_profile_title_key_p3_0">Your profile 3</string>
    <string name="lib_pref_frame_count_zsl_key">0</string>
    <string name="pref_has_checked_dual_ev_brightness">0</string>
    <string name="lib_gpu_luminance_threshold_key">0</string>
    <string name="lib_sharpen_default_h_3a_key"></string>
    <string name="pref_config_filename_key">CLEAN test 1.agc</string>
    <string name="lib_optimize_sky_key">Off (as in library)</string>
    <string name="pref_camera_picturesize_front_key">3264x2448</string>
    <string name="pref_manual_opmode_amber_key">0</string>
    <string name="pref_gcam_lens_logic_key">0</string>
    <string name="pref_imax_audio_enabled_key">0</string>
    <string name="lib_sabre_sharp_tuning_l13_key"></string>
    <string name="lib_highlight_fix_zsl_key">1</string>
    <string name="pref_social_app_com_facebook_orca">0</string>
    <string name="pref_satcct_c_key">1.0</string>
    <string name="lib_sabre_1_key">Off (as in library)</string>
    <string name="pref_show_cct_button_key">1</string>
    <string name="bb_key">1.828</string>
    <string name="lib_merge23_luma_dh_sabre_l4a_key">Off (as in library)</string>
    <string name="pref_watermark_logo_key">agc88.png</string>
    <string name="lib_custom_6_key_address">038F6DD0</string>
    <string name="lib_chroma_a_key"></string>
    <string name="lib_luma_dh_sabre_l1a_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_l6_key"></string>
    <string name="lib_custom_5_key_address">038F6DCC</string>
    <string name="lib_custom_9_key_address">025D27F0</string>
    <string name="pref_has_checked_ornament_mode">0</string>
    <string name="lib_luma_dm_sabre_l1a_key">Off (as in library)</string>
    <string name="lib_spatial_a_key"></string>
    <string name="pref_expcomp_ns_key">0</string>
    <string name="lib_merge23_luma_dl_sabre_l2_key">Off (as in library)</string>
    <string name="lib_skipmetadatacheck_key">1</string>
    <string name="lib_enable_color_key_p1_3">1</string>
    <string name="lib_enable_color_key_p1_2">1</string>
    <string name="lib_enable_color_key_p1_1">1</string>
    <string name="lib_enable_color_key_p1_0">1</string>
    <string name="pref_red_coeff_key">1.0</string>
    <string name="lib_enable_color_key_p1_4">1</string>
    <string name="lib_custom_patch_count_key_p8_0">10</string>
    <string name="lib_custom_patch_count_key_p8_1">10</string>
    <string name="lib_custom_patch_count_key_p8_2">10</string>
    <string name="lib_custom_patch_count_key_p8_3">10</string>
    <string name="lib_custom_20_key_title"></string>
    <string name="lib_custom_patch_count_key_p8_4">10</string>
    <string name="pref_enable_log_file_key">0</string>
    <string name="pref_white_level_key">0</string>
    <string name="lib_sharp_noise_model_key">Off (as in library)</string>
    <string name="pref_satcct_r_key">1.0</string>
    <string name="lib_sabre_sharp_tuning_radius_l8_key"></string>
    <string name="lib_bayer_noise_model_halide_3_key">Off (as in library)</string>
    <string name="lib_disable_safe_under_exposure_key">Off (as in library)</string>
    <string name="lib_profile_title_key_p1_4">Your profile 1</string>
    <string name="lib_profile_title_key_p1_3">Your profile 1</string>
    <string name="lib_profile_title_key_p1_2">Your profile 1</string>
    <string name="lib_profile_title_key_p1_1">Your profile 1</string>
    <string name="lib_profile_title_key_p1_0">Your profile 1</string>
    <string name="lib_custom_14_key_value">295CAF3F</string>
    <string name="lib_pref_satcct_key">1.0</string>
    <string name="lib_sabre_sharp_tuning_l7_key"></string>
    <string name="lib_custom_13_key_enabled">1</string>
    <string name="pref_satcct_b_key">1.0</string>
    <string name="pref_storage_saver_auto_disable">0</string>
    <string name="lib_smoothness_key">Off (as in library)</string>
    <string name="lib_luma_dh_sabre_l1b_key">Off (as in library)</string>
    <string name="pref_video_fps_p2018_key">FPS_60</string>
    <string name="pref_vibro_key">0</string>
    <string name="lib_raisr_large_key">Off (as in library)</string>
    <string name="pref_camera_raw_output_key">0</string>
    <string name="lib_chroma_b_key"></string>
    <string name="lib_bb_key">1.828</string>
    <string name="lib_hardjpgquality_key">100</string>
    <string name="lib_luma_dm_sabre_l1b_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_l14_key"></string>
    <string name="lib_merge23_luma_dl_sabre_l3_key">Off (as in library)</string>
    <string name="lib_rejected_denoise_multiplier_key">Off (as in library)</string>
    <string name="lib_allow_unknown_devices_key">Off (as in library)</string>
    <string name="lib_custom_15_key_value">A470A540</string>
    <string name="lib_merge23_luma_dm_sabre_l2_key">Off (as in library)</string>
    <string name="pref_video_fps_cm_key">FPS_30</string>
    <string name="lib_custom_17_key_enabled">1</string>
    <string name="lib_custom_28_key_value">08EFA752</string>
    <string name="lib_shasta_zsl_set_key">Off (as in library)</string>
    <string name="lib_custom_2_key_address">025D288C</string>
    <string name="lib_custom_27_key_value">E0F5030F</string>
    <string name="lib_robustness_key">Off (as in library)</string>
    <string name="pref_suffix_key"></string>
    <string name="lib_custom_16_key_title"></string>
    <string name="lib_custom_24_key_enabled">1</string>
    <string name="lib_merge23_luma_dm_sabre_l1_key">Off (as in library)</string>
    <string name="pref_awb_rg_coeff_key">1.0</string>
    <string name="pref_lens_title_key_1">UW</string>
    <string name="pref_lens_title_key_0">Main</string>
    <string name="pref_lens_title_key_3">Front</string>
    <string name="key_social_share_opt_in">0</string>
    <string name="pref_lens_title_key_2">Tele</string>
    <float name="camcorder.max_zoom" value="10.0" />
    <string name="key_ff_opt_in">0</string>
    <string name="pref_title_index">1</string>
    <string name="pref_has_checked_dual_ev_shadow">0</string>
    <string name="lib_sharp_mini_key">Off (as in library)</string>
    <string name="pref_cct_wb_intensity_key">1.0</string>
    <string name="lib_custom_20_key_enabled">0</string>
    <string name="pref_lens_title_key_4">(Logical) Main</string>
    <string name="lib_gpu_brightness_key">0</string>
    <string name="lib_p6_nm_gain_multiplier_key"></string>
    <string name="pref_merge_key_4">2</string>
    <string name="pref_merge_key_3">2</string>
    <string name="lib_gpu_vignette_start_key">0</string>
    <string name="lib_gb_key">0.085</string>
    <string name="lib_sabre_sharp_tuning_radius_l7_key"></string>
    <string name="pref_merge_key_0">2</string>
    <string name="pref_merge_key_2">2</string>
    <string name="pref_merge_key_1">2</string>
    <string name="pref_opmode_slowmo_key">0</string>
    <string name="lib_volume_processing_2_key">Off (as in library)</string>
    <string name="lib_hdr_ratio_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_details_l13_key"></string>
    <string name="lib_max_relative_tet_factor_key"></string>
    <string name="lib_softsharp_key">Off (as in library)</string>
    <string name="as_gr_key">4.9889366E-7</string>
    <string name="lib_custom_9_key_enabled">1</string>
    <string name="lib_enable_color_key_p6_2">1</string>
    <string name="lib_enable_color_key_p6_1">1</string>
    <string name="lib_enable_color_key_p6_0">1</string>
    <string name="lib_gpu_highlights_key">1.0</string>
    <string name="pref_camera_coach_key">0</string>
    <string name="lib_sharp_distrib_3_key">Off (as in library)</string>
    <string name="lib_sharpen_default_m_1_key"></string>
    <string name="lib_enable_color_key_p6_4">1</string>
    <string name="lib_enable_color_key_p6_3">1</string>
    <string name="lib_custom_1_key_enabled">1</string>
    <string name="lib_sabre_sharp_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_l8_key"></string>
    <string name="lib_contrast_black_key">Off (as in library)</string>
    <string name="lib_merge23_luma_dl_sabre_l1a_key">Off (as in library)</string>
    <string name="lib_iso_max_zsl_analog_key">Off (as in library)</string>
    <string name="lib_custom_32_key_title"></string>
    <int name="tooltip_impression_count_for_long_press" value="1" />
    <string name="lib_highlight_key_p0_0">4096 (Default)</string>
    <string name="lib_smoothing_sabre_key"></string>
    <string name="lib_highlight_key_p0_4">4096 (Default)</string>
    <string name="lib_smoothing_temporal_key">Off (as in library)</string>
    <string name="lib_highlight_key_p0_2">4096 (Default)</string>
    <string name="lib_highlight_key_p0_3">4096 (Default)</string>
    <string name="lib_merge23_luma_dm_sabre_l3_key">Off (as in library)</string>
    <string name="pref_camera_picturesize_back_key">4096x3072</string>
    <string name="lib_luma_dh_sabre_l1_key">Off (as in library)</string>
    <string name="lib_polysharp_radius_small_key"></string>
    <string name="lib_custom_6_key_value">02103E1E</string>
    <string name="lib_sabre_contrast_sharp_key">Off (as in library)</string>
    <string name="pref_watermark_title_key">Xiaomi 13 | AGC 9.1 | v1 | @antykat</string>
    <string name="do_gr_key">-8.484603E-8</string>
    <string name="pref_device_key">0</string>
    <string name="lib_allow_spatial_rgb_key">Off (as in library)</string>
    <string name="black_level_2_key">64.0</string>
    <string name="pref_ois_data_key">1</string>
    <string name="pref_expcomp_key_0">0</string>
    <string name="lib_min_short_frames_key"></string>
    <string name="lib_sharpen_default_h_1_key"></string>
    <string name="pref_update_color_online_key">0</string>
    <string name="lib_pref_awbratio_key">0</string>
    <string name="lib_spatial_b_key"></string>
    <string name="lib_highlight_fix_2_key">1</string>
    <string name="lib_pref_satcct_r_key_p1_0">1.0</string>
    <set name="pref_camera_id_list_key">
        <string>0</string>
        <string>1</string>
        <string>2</string>
        <string>3</string>
        <string>7</string>
    </set>
    <string name="lib_sharpen_default_vl_1_key"></string>
    <string name="lib_baseframe_sharpness_threshold_key">Off (as in library)</string>
    <string name="info_model_key">2211133G</string>
    <string name="lib_pref_color_transform_key">0</string>
    <string name="lib_sabre_sharp_tuning_radius_l16_key"></string>
    <string name="lib_custom_3_key_title"></string>
    <string name="pref_dev_switch_hidden">0</string>
    <string name="lib_sabre_sharp_tuning_details_l5_key"></string>
    <string name="lib_luma_dh_sabre_l2a_key">Off (as in library)</string>
    <string name="pref_vffps_low_key">15</string>
    <string name="lib_iso_expo_tuning_key"></string>
    <string name="info_manuf_key">Xiaomi</string>
    <string name="lib_pref_satcct_g_key">1.0</string>
    <string name="lib_lut_key_p0_0">null</string>
    <string name="lib_sabre_sharp_tuning_l11_key"></string>
    <string name="pref_af_mode_front">0</string>
    <string name="lib_custom_10_key_value">E0F5034F</string>
    <string name="lib_enable_color_key_p4_0">1</string>
    <string name="lib_luma_dm_sabre_l5_key">Off (as in library)</string>
    <string name="lib_apply_portrait_matting_key">Off (as in library)</string>
    <string name="lib_enable_color_key_p4_4">1</string>
    <string name="lib_raw_sharpen_b_key">Off (as in library)</string>
    <string name="lib_custom_14_key_title"></string>
    <string name="pref_curve_enable_key">0</string>
    <string name="lib_enable_color_key_p4_3">1</string>
    <string name="lib_enable_color_key_p4_2">1</string>
    <string name="lib_enable_color_key_p4_1">1</string>
    <string name="lib_sabre_sharp_tuning_l12_key"></string>
    <string name="black_level_1_key">64.0</string>
    <string name="as_r_key">4.9889366E-7</string>
    <string name="lib_lut_key_p0_3">null</string>
    <string name="lib_lut_key_p0_4">null</string>
    <string name="lib_lut_key_p0_2">null</string>
    <string name="lib_pref_red_coeff_key_p1_0">1.0</string>
    <string name="lib_custom_23_key_address">0265D294</string>
    <string name="lib_merge23_luma_dm_sabre_l4_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_details_l14_key"></string>
    <string name="lib_sharpen_default_l_3_key"></string>
    <string name="lib_pref_y_hue_key">0</string>
    <string name="lib_custom_21_key_address">02AB360C</string>
    <string name="lib_savannah_merge_key">Off (as in library)</string>
    <string name="lib_sharpen_default_vl_2_key"></string>
    <string name="pref_metering_mode_key">0</string>
    <string name="lib_fixraw16merge_key">Off (as in library)</string>
    <string name="pref_photo_grayscale_key">0</string>
    <string name="lib_br_key">0.093</string>
    <string name="lib_merge23_luma_dm_sabre_l4b_key">Off (as in library)</string>
    <string name="lib_luma_dh_sabre_l2_key">Off (as in library)</string>
    <string name="lib_gpu_rgb_red_key">0</string>
    <string name="lib_custom_12_key_value">03D02B1E</string>
    <string name="pref_opmode_photo_key">0</string>
    <string name="lib_pref_r_hue_key_p1_0">0.0</string>
    <string name="pref_zoom_out_command_string">20</string>
    <string name="lib_lut_id_key_p0_0">-1</string>
    <string name="lib_custom_12_key_address">03713994</string>
    <string name="lib_motion_scale_factor_key">Off (as in library)</string>
    <string name="pref_has_checked_measure_mode">0</string>
    <string name="lib_patch_profile_key">3</string>
    <string name="lib_custom_5_key_title"></string>
    <string name="pref_date_key">yyyyMMdd_HHmmssSSS</string>
    <string name="lib_custom_10_key_address">025D27EC</string>
    <string name="lib_lut_id_key_p0_4">-1</string>
    <string name="lib_custom_2_key_value">08EFA752</string>
    <string name="lib_lut_id_key_p0_3">-1</string>
    <string name="lib_pref_c_hue_key">0</string>
    <string name="lib_lut_id_key_p0_2">-1</string>
    <string name="lib_temporal_a_key"></string>
    <string name="info_android_version_key">14</string>
    <string name="pref_color_transform_key_0">14</string>
    <string name="lib_custom_32_key_value">0CF02D1E</string>
    <string name="pref_color_transform_key_2">14</string>
    <string name="pref_color_transform_key_1">14</string>
    <string name="lib_sabre_max_scale_factor_key">Off (as in library)</string>
    <string name="lib_shastafactor_key"></string>
    <string name="lib_denoise_smoothing_key">Off (as in library)</string>
    <string name="pref_track_focus_key">1</string>
    <string name="pref_color_transform_key_4">14</string>
    <string name="lib_sabre_sharp_tuning_radius_l17_key"></string>
    <string name="pref_show_curve_button_key">1</string>
    <string name="lib_luma_dm_sabre_l3b_key">Off (as in library)</string>
    <string name="lib_downsample_by_2_before_merge_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_l9_key"></string>
    <string name="pref_prefix_key">⚛️antykat_v1_Xiaomi13_AGC9.1_</string>
    <string name="lib_sharpen_default_h_2_key"></string>
    <string name="lib_sabre_sharp_tuning_details_l6_key"></string>
    <string name="lib_sharpen_default_m_2a_key"></string>
    <string name="lib_merge23_luma_dh_sabre_l5_key">Off (as in library)</string>
    <string name="lib_custom_7_key_enabled">1</string>
    <string name="lib_custom_18_key_address">00A0C3B0</string>
    <string name="lib_custom_8_key_value">E0F5034F</string>
    <string name="lib_merge23_luma_dm_sabre_l5_key">Off (as in library)</string>
    <string name="lib_tone_key">Off (as in library)</string>
    <string name="lib_custom_lib_open_key">gcastartup</string>
    <string name="co_r_key">1.9878738E-12</string>
    <string name="do_gb_key">-8.484603E-8</string>
    <boolean name="pref_disabled_discard_frames" value="false" />
    <string name="lib_custom_10_key_title"></string>
    <string name="lib_luma_dm_sabre_l4_key">Off (as in library)</string>
    <string name="pref_frame_count_key_3">20</string>
    <string name="lib_custom_7_key_title"></string>
    <string name="pref_frame_count_key_2">20</string>
    <string name="lib_sharp_distrib_rad_1_key">Off (as in library)</string>
    <string name="lib_fine_spatial_max_2_key">Off (as in library)</string>
    <string name="pref_photo_watermark_key">0</string>
    <string name="pref_frame_count_key_4">20</string>
    <string name="lib_initial_zoom_key">1.0</string>
    <string name="pref_frame_count_key_1">20</string>
    <string name="pref_frame_count_key_0">20</string>
    <string name="gg_key">1.062</string>
    <string name="black_level_0_key">64.0</string>
    <string name="pref_y_hue_key">0</string>
    <string name="lib_hdr_overall_lightness_key">Off (as in library)</string>
    <string name="pref_manual_opmode_time_lapse_key">0</string>
    <string name="lib_custom_8_key_title"></string>
    <string name="lib_custom_8_key_address">025D27EC</string>
    <string name="lib_pref_green_coeff_key_p1_0">1.0</string>
    <string name="lib_gg_key">1.062</string>
    <string name="lib_sharpen_default_m_3_key"></string>
    <string name="lib_sharpen_default_vl_3_key"></string>
    <string name="pref_manual_opmode_ns_key">0</string>
    <string name="lib_gpu_vibrance_key">1.2</string>
    <string name="lib_sharp_distrib_1_key">Off (as in library)</string>
    <string name="lib_better_color_wiener_sabre_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_details_l15_key"></string>
    <string name="pref_iso_noise_key">0</string>
    <string name="pref_mars_enabled">0</string>
    <string name="lib_luma_dm_sabre_l3a_key">Off (as in library)</string>
    <string name="lib_custom_12_key_title"></string>
    <string name="lib_sabre_sharp_tuning_details_l18_key"></string>
    <string name="lib_custom_9_key_title"></string>
    <string name="lib_merge23_luma_dh_sabre_l4_key">Off (as in library)</string>
    <string name="lib_custom_patch_count_key_p0_0">10</string>
    <string name="pref_micro_video_height_key">480</string>
    <string name="lib_custom_patch_count_key_p0_1">10</string>
    <string name="lib_custom_patch_count_key_p0_2">10</string>
    <string name="lib_temporal_b_key"></string>
    <string name="lib_custom_patch_count_key_p0_3">10</string>
    <string name="lib_custom_patch_count_key_p0_4">10</string>
    <string name="lib_ldr_highlight_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_details_l3_key"></string>
    <string name="lib_pref_cct_wb_offset_key">1.0</string>
    <string name="lib_luma_dm_sabre_l1_key">Off (as in library)</string>
    <string name="lib_luma_dl_sabre_l2b_key">Off (as in library)</string>
    <string name="lib_sharpen_default_l_2_key"></string>
    <string name="lib_contrast_2_key">Off (as in library)</string>
    <string name="lib_min_bracketing_frames_key"></string>
    <string name="pref_c_hue_key">0</string>
    <string name="lib_custom_26_key_address">025D4814</string>
    <string name="pref_camera_grid_lines_mode_new">3</string>
    <string name="lib_merge23_luma_dh_sabre_l2a_key">Off (as in library)</string>
    <string name="as_gb_key">4.9889366E-7</string>
    <string name="pref_micro_video_width_key">640</string>
    <string name="lib_custom_6_key_title"></string>
    <string name="pref_color_theme_key">0</string>
    <string name="lib_luma_dh_sabre_l5a_key">Off (as in library)</string>
    <string name="pref_manual_focus_infinity_key">0</string>
    <string name="lib_raw_sharpen_a_key">Off (as in library)</string>
    <string name="pref_preview_key">0</string>
    <string name="pref_exposure_control_key">0</string>
    <string name="lib_custom_29_key_address">02AB42C8</string>
    <string name="lib_sabre_sharp_tuning_radius_l18_key"></string>
    <string name="lib_sharp_distrib_rad_2_key">Off (as in library)</string>
    <string name="lib_enable_color_key_p8_0">1</string>
    <string name="lib_custom_4_key_value">08EFA752</string>
    <string name="lib_sharp_legibility_key">Off (as in library)</string>
    <string name="lib_highlight_key">Off (as in library)</string>
    <string name="lib_enable_color_key_p8_4">1</string>
    <string name="lib_enable_color_key_p8_3">1</string>
    <string name="pref_has_checked_tiara_mode">0</string>
    <string name="lib_enable_color_key_p8_2">1</string>
    <string name="lib_enable_color_key_p8_1">1</string>
    <string name="lib_polysharp_radius_large_key"></string>
    <string name="pref_camera_cd_indicator_enabled_key">1</string>
    <string name="lib_custom_11_key_enabled">1</string>
    <string name="lib_blurpreview_key">1</string>
    <string name="pref_social_app_com_facebook_katana">0</string>
    <string name="lib_init_params_key">Off (as in library)</string>
    <string name="lib_fine_spatial_max_1_key">Off (as in library)</string>
    <string name="lib_profile_title_key_p8_4">Your profile 8</string>
    <string name="lib_profile_title_key_p8_3">Your profile 8</string>
    <string name="lib_profile_title_key_p8_2">Your profile 8</string>
    <string name="lib_profile_title_key_p8_1">Your profile 8</string>
    <string name="pref_has_checked_social_share_toggle">1</string>
    <string name="lib_profile_title_key_p8_0">Your profile 8</string>
    <string name="lib_sabre_sharp_tuning_details_l16_key"></string>
    <string name="lib_sharpen_default_vh_1a_key"></string>
    <string name="lib_sharpen_default_vh_3_key"></string>
    <string name="lib_tone_custom_key"></string>
    <string name="pref_social_app_com_whatsapp">0</string>
    <string name="lib_sharp_distrib_2_key">Off (as in library)</string>
    <string name="lib_custom_19_key_enabled">1</string>
    <string name="lib_sharpen_default_m_2_key"></string>
    <string name="lib_luma_dm_sabre_l3_key">Off (as in library)</string>
    <string name="lib_pref_satcct_key_p0_4">1.0</string>
    <string name="lib_merge23_luma_dh_sabre_l2b_key">Off (as in library)</string>
    <string name="pref_social_app_org_thoughtcrime_securesms">0</string>
    <string name="lib_pref_satcct_key_p0_0">1.0</string>
    <string name="lib_pref_satcct_key_p0_3">1.0</string>
    <string name="lib_pref_satcct_key_p0_2">1.0</string>
    <string name="lib_pref_manual_iso_noise_key">6400</string>
    <string name="pref_global_hue_key">0</string>
    <string name="lib_custom_patch_count_key_p2_0">10</string>
    <string name="lib_custom_patch_count_key_p2_1">10</string>
    <string name="lib_custom_patch_count_key_p2_2">10</string>
    <string name="lib_custom_patch_count_key_p2_3">10</string>
    <string name="lib_custom_patch_count_key_p2_4">10</string>
    <string name="lib_portrait_use_opencl_depth_key">Off (as in library)</string>
    <string name="lib_contrast_1_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_details_l17_key"></string>
    <string name="lib_luma_dh_sabre_l2b_key">Off (as in library)</string>
    <string name="lib_sabre_sharp_tuning_details_l4_key"></string>
    <string name="pref_watermark_bg_key">1</string>
    <string name="lib_custom_22_key_enabled">1</string>
    <string name="lib_gamma_key">Off (as in library)</string>
    <string name="lib_merge23_luma_dh_sabre_l3_key">Off (as in library)</string>
    <string name="lib_custom_32_key_address">02CC3D04</string>
    <string name="lib_compress_merged_dng_key">Off (as in library)</string>
    <string name="lib_pref_satcct_g_key_p0_0">1.0</string>
    <string name="lib_sharpen_default_l_1a_key"></string>
    <string name="lib_pref_satcct_g_key_p0_2">1.0</string>
    <string name="lib_pref_satcct_g_key_p0_3">1.0</string>
    <string name="lib_pref_satcct_g_key_p0_4">1.0</string>
    <string name="pref_green_coeff_key">1.0</string>
    <string name="lib_custom_11_key_title"></string>
    <string name="lib_merge23_luma_dl_sabre_l5a_key">Off (as in library)</string>
    <string name="lib_pref_r_hue_key">0</string>
    <string name="lib_sabre_sharp_tuning_l10_key"></string>
    <string name="lib_custom_5_key_value">01F02D1E</string>
    <string name="lib_custom_15_key_address">00A0C3A4</string>
    <string name="lib_sharpen_default_l_1_key"></string>
    <string name="lib_luma_dl_sabre_l5a_key">Off (as in library)</string>
    <string name="lib_custom_4_key_enabled">1</string>
    <string name="pref_video_resolution">RES_1080P</string>
    <string name="pref_camera_advice_settings">1</string>
</map>
